branches:
  only:
    - master
    - testing
language: c
compiler: gcc
install:
  - sudo apt-get install texinfo
script:
  - git submodule init
  - git submodule update
  - make dependencies
  - make build
  - make examples
  - build/examples/knapsack examples/knapsack/instances/mknapcb0.txt
