# Site settings
title: Evolve
email: earaujoassis@gmail.com
description: A library for Evolutionary Computation algorithms
baseurl: "/evolve"
url: "https://earaujoassis.github.io"
creators_website: "http://earaujoassis.com"
twitter_username: earaujoassis
github_username:  earaujoassis
github_project: evolve
source: .
destination: ./_build

# Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'bower.json', 'README.md']
markdown: kramdown
